eval_config_override: ./configs/examples/lighteval-config.yaml
batch_size: 16
eval_interval: 3
generation:
  n_samples: 1
  sampler: greedy
  seed: 42
  temperature: 0.0
  top_k: 0
  top_p: 1.0
  use_cache: true
local_checkpoint_dir: ./smol-playbook-checkpoints
logging:
  local_output_path: ./eval_results
logs_path: ./eval_results/logs
nanotron_path: ./
parallelism:
  context_parallel_size: 1
  dp: 1
  expert_parallel_size: 1
  pp: 1
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: false
  tp_recompute_allgather: true
slurm:
  cpus_per_task: 1
  gpus_per_node: 1
  hf_cache: ~/.cache/huggingface
  partition: debug
  qos: low
  reservation: null
  time: '24:00:00'
slurm_script_dir: ./eval_results/launch-config
tasks:
  dataset_loading_processes: 8
  tasks: lighteval|agieval:aqua-rat|5|0
upload_to_wandb: false
