[project]
name = "nanotron"
version = "0.4"
description = "Minimalistic Large Language Model Training and Finetuning"
authors = [
    {name = "Nouamane Tazi", email="nouamane@huggingface.co"},
    {name = "Thomas Wang", email="thomas.wang@huggingface.co"},
    {name = "Kunhao Zheng", email="kunhao@huggingface.co"},
    {name = "Thomas Wolf", email="thomas@huggingface.co"},
]
readme = "README.md"
requires-python = "~=3.11.0"
classifiers = [
    "Topic :: Software Development"
]
dependencies = [
    "torch>=2.6.0",
    "pyyaml",
    "numpy",
    "packaging",
    "safetensors",
    "dacite",
    "tqdm",
    "datasets<=4.5.0",
    "torchtyping",
    "lighteval",
    "pillow",
    "matplotlib>=3.10.8",
    "seaborn>=0.13.2",
]

[tool.ruff]
line-length = 119
ignore = ["C901","E501"] # E501 ignores length violation handled by black
select = ["C","E","F","I","W"]
ignore-init-module-imports = true

[tool.uv.extra-build-dependencies]
flash-attn = ["setuptools", "wheel", "torch", "psutil"]

[tool.uv]
no-build-isolation-package = ['flash-attn']

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch = {index = "pytorch"}
triton = {index = "pytorch"}
lighteval = { git = "https://github.com/Fab-Inc/lighteval.git", rev = "develop-earlyversion"}
datatrove = { git = "https://github.com/huggingface/datatrove.git", rev = "7939834eb71173181c658798d386c477a01342af"}
fab-qurating = { git = "https://github.com/Fab-Inc/fab-qurating.git", rev = "do-adapt-oli-run-minimal-data" }

[dependency-groups]
dev = [
    "wheel",
    "psutil",
    "pre-commit",
    "pylint",
    "ipykernel",
]

test = [
    "pytest",
    "pytest-xdist",
    "pytest-coverage",
]

fast-modeling = [
    "ninja",
    "triton==3.*",
    "setuptools",
    "flash-attn>=2.5.0,<2.7.0",
    # "nv-grouped-gemm@git+https://github.com/fanshiqing/grouped_gemm@main"
]

nanosets = [
     "transformers<5",
     "datatrove[io,processing]",
     "numba",
]

s3 = [
    "boto3",
    "botocore[crt]",
    "s3fs>=2021",
    "s5cmd",
]

az = [
    "cloudpathlib[azure]",
    "python-dotenv",
    "adlfs",
    "fab-qurating",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/nanotron"]

[tool.pytest.custom_ini]
norecursedirs="tests/helpers"
