ClusterName=localcluster
SlurmctldHost=localhost
ProctrackType=proctrack/linuxproc
SlurmUser=slurm
StateSaveLocation=/var/lib/slurm-llnl/slurmctld
GresTypes=gpu
NodeName=lhtraineval NodeHostName=localhost CPUs=24 RealMemory=240000 State=UNKNOWN Gres=gpu:h200
PartitionName=eval Nodes=lhtraineval Default=YES MaxTime=INFINITE State=UP