s3_save_path: s3://qurating-evals-183631302286-eu-west-2-an/base-run-1200
batch_size: 128
eval_interval: 100
generation:
  n_samples: 1
  sampler: greedy
  seed: 42
  temperature: 0.0
  top_k: 0
  top_p: 1.0
  use_cache: true
local_checkpoint_dir: ./checkpoints/smol-playbook-checkpoints
logging:
  local_output_path: ./eval_results
logs_path: ./eval_results/logs
nanotron_path: ./
parallelism:
  context_parallel_size: 1
  dp: 1
  expert_parallel_size: 1
  pp: 1
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: false
  tp_recompute_allgather: true
slurm:
  cpus_per_task: 1
  gpus_per_node: 1
  hf_cache: ~/.cache/huggingface
  partition: eval
  qos: low
  reservation: null
  time: '24:00:00'
slurm_script_dir: ./eval_results/launch-config
tasks:
  custom_tasks: nanotron.eval.fabai.custom_tasks
  dataset_loading_processes: 1
  tasks: custom|pedagogy_cdpk_cloze|0|0,leaderboard|hellaswag|0|1,custom|arc_cf|0|1,custom|mmlu_cf|0|1,custom|mmlu_pro_cf|0|1,custom|boolq_cf|0|1,custom|commonsenseqa_cf|0|1,leaderboard|winogrande|0|1,custom|openbookqa_cf|0|1
upload_to_wandb: true
wandb_entity: fabdata
wandb_project: qurating-smol-playbook
