ClusterName=localcluster
SlurmctldHost=localhost
ProctrackType=proctrack/linuxproc
SlurmUser=slurm
StateSaveLocation=/var/lib/slurm-llnl/slurmctld
GresTypes=gpu
NodeName=localhost NodeHostName=localhost CPUs=208 RealMemory=1860000 State=UNKNOWN Gres=gpu:h100
PartitionName=eval Nodes=localhost Default=YES MaxTime=INFINITE State=UP