ClusterName=localcluster
SlurmctldHost=localhost
ProctrackType=proctrack/linuxproc
SlurmUser=slurm
StateSaveLocation=/var/lib/slurm-llnl/slurmctld
GresTypes=gpu
NodeName=lhtrain NodeHostName=localhost CPUs=160 RealMemory=640000 State=UNKNOWN Gres=gpu:h100:7
NodeName=lheval NodeHostName=localhost CPUs=160 RealMemory=640000 State=UNKNOWN Gres=gpu:h100:1
PartitionName=train Nodes=lhtrain Default=YES MaxTime=INFINITE State=UP
PartitionName=eval Nodes=lheval Default=YES MaxTime=INFINITE State=UP