ClusterName=localcluster
SlurmctldHost=localhost
ProctrackType=proctrack/linuxproc
SlurmUser=slurm
StateSaveLocation=/var/lib/slurm-llnl/slurmctld
GresTypes=gpu
NodeName=localhost CPUs=20 RealMemory=240000 State=UNKNOWN Gres=gpu:h100:1
PartitionName=debug Nodes=ALL Default=YES MaxTime=INFINITE State=UP